### ISSUE TITLE
Pages don't load

### ISSUE THREAD

**Issue by HeidiSeibold** [jbryer/psa#1]
For example
http://jason.bryer.org/psa/intro/stratification.html
does not load correctly.

The geen loading bar starts growing but at some point stops. 
![screenshot from 2016-10-12 12 55 48](https://cloud.githubusercontent.com/assets/14146757/19307519/38a06db6-907b-11e6-8ca2-56e6f6602d8a.png)

**Comment by jbryer** [comment]
Finally getting around to fixing this. Site is now available at https://psa.bryer.org. Hoping to make significant additions to this repo over the coming months.
